# Uncomment the next line to define a global platform for your project
platform :ios, '12'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "AppAuth" , "1.7.6"
  pod "KServices" , "0.2.2"

  # Pods for iosApp

end
